<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateExpertisesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('expertises', function (Blueprint $table) {

            $table->bigIncrements('id')->unique();
            $table->integer('abrirT')->nullable();
            $table->integer('abrirG')->nullable();
            $table->integer('abrirO')->nullable();
            $table->string('abrirK')->nullable();
            $table->integer('acrobT')->nullable();
            $table->integer('acrobG')->nullable();
            $table->integer('acrobO')->nullable();
            $table->string('acrobK')->nullable();
            $table->integer('adesT')->nullable();
            $table->integer('adesG')->nullable();
            $table->integer('adesO')->nullable();
            $table->string('adesK')->nullable();
            $table->integer('arteT')->nullable();
            $table->integer('arteG')->nullable();
            $table->integer('arteO')->nullable();
            $table->string('arteK')->nullable();
            $table->integer('atuaT')->nullable();
            $table->integer('atuaG')->nullable();
            $table->integer('atuaO')->nullable();
            $table->string('atuaK')->nullable();
            $table->integer('atuaT1')->nullable();
            $table->integer('atuaG1')->nullable();
            $table->integer('atuaO1')->nullable();
            $table->string('atuaK1')->nullable();
            $table->integer('atuaT2')->nullable();
            $table->integer('atuaG2')->nullable();
            $table->integer('atuaO2')->nullable();
            $table->string('atuaK2')->nullable();
            $table->integer('avaliaT')->nullable();
            $table->integer('avaliaG')->nullable();
            $table->integer('avaliaO')->nullable();
            $table->string('avaliaK')->nullable();
            $table->integer('blefaT')->nullable();
            $table->integer('blefaG')->nullable();
            $table->integer('blefaO')->nullable();
            $table->string('blefaK')->nullable();
            $table->integer('cavalgaT')->nullable();
            $table->integer('cavalgaG')->nullable();
            $table->integer('cavalgaO')->nullable();
            $table->string('cavalgaK')->nullable();
            $table->integer('concentraT')->nullable();
            $table->integer('concentraG')->nullable();
            $table->integer('concentraO')->nullable();
            $table->string('concentraK')->nullable();
            $table->integer('conheceT')->nullable();
            $table->integer('conheceG')->nullable();
            $table->integer('conheceO')->nullable();
            $table->string('conheceK')->nullable();
            $table->integer('conheceT1')->nullable();
            $table->integer('conheceG1')->nullable();
            $table->integer('conheceO1')->nullable();
            $table->string('conheceK1')->nullable();
            $table->integer('conheceT2')->nullable();
            $table->integer('conheceG2')->nullable();
            $table->integer('conheceO2')->nullable();
            $table->string('conheceK2')->nullable();
            $table->integer('curaT')->nullable();
            $table->integer('curaG')->nullable();
            $table->integer('curaO')->nullable();
            $table->string('curaK')->nullable();
            $table->integer('decifraT')->nullable();
            $table->integer('decifraG')->nullable();
            $table->integer('decifraO')->nullable();
            $table->string('decifraK')->nullable();
            $table->integer('diplomaT')->nullable();
            $table->integer('diplomaG')->nullable();
            $table->integer('diplomaO')->nullable();
            $table->string('diplomaK')->nullable();
            $table->integer('disfarceT')->nullable();
            $table->integer('disfarceG')->nullable();
            $table->integer('disfarceO')->nullable();
            $table->string('disfarceK')->nullable();
            $table->integer('equilT')->nullable();
            $table->integer('equilG')->nullable();
            $table->integer('equilO')->nullable();
            $table->string('equilK')->nullable();
            $table->integer('escalaT')->nullable();
            $table->integer('escalaG')->nullable();
            $table->integer('escalaO')->nullable();
            $table->string('escalaK')->nullable();
            $table->integer('escondeT')->nullable();
            $table->integer('escondeG')->nullable();
            $table->integer('escondeO')->nullable();
            $table->string('escondeK')->nullable();
            $table->integer('fasificaT')->nullable();
            $table->integer('falsificaG')->nullable();
            $table->integer('falsificaO')->nullable();
            $table->string('falsificaK')->nullable();
            $table->integer('furtivoT')->nullable();
            $table->integer('furtivoG')->nullable();
            $table->integer('furtivoO')->nullable();
            $table->string('furtivoK')->nullable();
            $table->integer('idenT')->nullable();
            $table->integer('idenG')->nullable();
            $table->integer('idenO')->nullable();
            $table->string('idenK')->nullable();
            $table->integer('intimidaT')->nullable();
            $table->integer('intimidaG')->nullable();
            $table->integer('intimidaO')->nullable();
            $table->string('intimidaK')->nullable();
            $table->integer('nadaT')->nullable();
            $table->integer('nadaG')->nullable();
            $table->integer('nadaO')->nullable();
            $table->string('nadaK')->nullable();
            $table->integer('observaT')->nullable();
            $table->integer('observaG')->nullable();
            $table->integer('observaO')->nullable();
            $table->string('observaK')->nullable();
            $table->integer('obterT')->nullable();
            $table->integer('obterG')->nullable();
            $table->integer('obterO')->nullable();
            $table->string('obterK')->nullable();
            $table->integer('oficioT')->nullable();
            $table->integer('oficioG')->nullable();
            $table->integer('oficioO')->nullable();
            $table->string('oficioK')->nullable();
            $table->integer('operarT')->nullable();
            $table->integer('operarG')->nullable();
            $table->integer('operarO')->nullable();
            $table->string('operarK')->nullable();
            $table->integer('ouvirT')->nullable();
            $table->integer('ouvirG')->nullable();
            $table->integer('ouvirO')->nullable();
            $table->string('ouvirK')->nullable();
            $table->integer('procuraT')->nullable();
            $table->integer('procuraG')->nullable();
            $table->integer('procuraO')->nullable();
            $table->string('procuraK')->nullable();
            $table->integer('profissaoT')->nullable();
            $table->integer('profissaoG')->nullable();
            $table->integer('profissaoO')->nullable();
            $table->string('profissaoK')->nullable();
            $table->integer('prestT')->nullable();
            $table->integer('prestG')->nullable();
            $table->integer('prestO')->nullable();
            $table->string('prestK')->nullable();
            $table->integer('saltarT')->nullable();
            $table->integer('saltarG')->nullable();
            $table->integer('saltarO')->nullable();
            $table->string('saltarK')->nullable();
            $table->integer('sentirT')->nullable();
            $table->integer('sentirG')->nullable();
            $table->integer('sentirO')->nullable();
            $table->string('sentirK')->nullable();
            $table->integer('sobreT')->nullable();
            $table->integer('sobreG')->nullable();
            $table->integer('sobreO')->nullable();
            $table->string('sobreK')->nullable();
            $table->integer('usacordaT')->nullable();
            $table->integer('usacordaG')->nullable();
            $table->integer('usacordaO')->nullable();
            $table->string('usacordaK')->nullable();
            $table->integer('usarmagicoT')->nullable();
            $table->integer('usarmagicoG')->nullable();
            $table->integer('usarmagicoO')->nullable();
            $table->string('usarmagicoK')->nullable();
            $table->integer('otherT')->nullable();
            $table->integer('otherG')->nullable();
            $table->integer('otherO')->nullable();
            $table->string('otherK')->nullable();
            $table->integer('otherT1')->nullable();
            $table->integer('otherG1')->nullable();
            $table->integer('otherO1')->nullable();
            $table->string('otherK1')->nullable();
            $table->integer('otherT2')->nullable();
            $table->integer('otherG2')->nullable();
            $table->integer('otherO2')->nullable();
            $table->string('otherK2')->nullable();

            $table->timestamps();

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('expertises');
    }
}
